version: '3'
services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"